import localFont from "next/font/local";
import "./globals.css";
import Header from "./header/page";
import { Montserrat } from "next/font/google";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"], // Виберіть потрібні ваги
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} `}>
        <div>
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                maxWidth: "50rem",
                width: "100%",
                height: "5rem",
                fontSize: "1.5rem",
              }, // Налаштовуємо ширину
            }}
          />
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
