import localFont from "next/font/local";
import "./globals.css";
import Header from "./header/page";
import { Montserrat } from "next/font/google";
import Hero from "./hero/page";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"], // Виберіть потрібні ваги
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} `}>
        <div className="container">
          <Header />
          <Hero />
          {children}
        </div>
      </body>
    </html>
  );
}
